FROM ghcr.io/mlflow/mlflow:v3.5.0

# Install PostgreSQL client library and AWS S3 support
USER root
RUN pip install --no-cache-dir psycopg2-binary boto3

# Switch back to default user if needed
USER 1000
